export const GET_ALL_COUNTRY_LIST_REQUEST = "GET_ALL_COUNTRY_LIST_REQUEST";
export const GET_ALL_COUNTRY_LIST_SUCCESS = "GET_ALL_COUNTRY_LIST_SUCCESS";
export const GET_ALL_COUNTRY_LIST_ERROR = "GET_ALL_COUNTRY_LIST_ERROR";

export const GET_COUNTRY_CODE_DATA_REQUEST = "GET_COUNTRY_CODE_DATA_REQUEST";
export const GET_COUNTRY_CODE_DATA_SUCCESS = "GET_COUNTRY_CODE_DATA_SUCCESS";
export const GET_COUNTRY_CODE_DATA_ERROR = "GET_COUNTRY_CODE_DATA_ERROR";
